maxmemory 512mb 
maxmemory-policy allkeys-lru
appendonly yes
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
replica-lazy-flush yes
lazyfree-lazy-user-del yes
# unixsocket /tmp/docker/redis.sock
# unixsocketperm 777
